language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec
notifications:
  slack:
    rooms:
      - secure: pb6HATvU9tjLxeGnN49HT5R6m3/eeS3Sj0F3BOb0zX0BSKAOj5NRjVUAnFTsViUYXe1MFlNhQqulKezdHUqamJyjMatTqOzqJjC1bxBCrVJ3VWv28NQIrEXRMDCDOA+oWbvW7F33PKHOkhcKl0HC+Sxz0CZwCsVBdgfbYAm//qeuGRlpZcHX7raroItGXyPVBdOhQlWP2gKj08/j/39eoCJycnmBeYD8mTXf3uxzYkmM9HoKAKUFWO8Js7gqJoHvG00I3mKiZzH6zgRD8A0QUTkxO0X+vKPUU1oZKfn4tpkRv6ehyvl6AZAZ0fd+MUqA3zmoLl5xpCckVXuttgzsSZCQq4ehJMx13N4YZ6JTAfil4X8dM55TrI7Ynz9rD5RowxOB4MVPwwoNg0bDpKWeAw11lJIyGCkSkTFHsAEXfM4FOJeg5sTEauF2d7TsxTG4yAJiGfBy3G3m9Zs8Ee1umBRpyqS86OlgCOqe5VxaSBQmF6LD/xLT0+Fjdy1hXKwcaRlquOPCGc8j05A3OXvsH6P6ilHUgylLc12TqDmaFbC0HzZ6LuJG6+rxap+d0aE30J6jvZh9Z66O79KgeQad4qKRmHomscCe8YIYxEDsF1KDtPd921w1ZhXwte60CY+pH2zR33TZqJnsjD7LAsnOPo02/uunxp5+9pWlzwrUJno=
    on_success: change
    on_failure: always
