AWS_KEY: <%= ENV['AWS_KEY'] %>
AWS_SECRET: <%= ENV['AWS_SECRET'] %>
SQS_QUEUE_URL: <%= ENV['SQS_QUEUE_URL'] %>
POLLING_INTERVAL_SECONDS: <%= ENV['POLLING_INTERVAL_SECONDS'] %>
MINIMUM_MESSAGE_AGE_SECONDS: <%= ENV['MINIMUM_MESSAGE_AGE_SECONDS'] %>
SCSB_API_URL: <%= ENV['SCSB_API_URL'] %>
SCSB_API_KEY: <%= ENV['SCSB_API_KEY'] %>
NYPL_OAUTH_KEY: <%= ENV['NYPL_OAUTH_KEY'] %>
NYPL_OAUTH_URL: <%= ENV['NYPL_OAUTH_URL'] %>
NYPL_OAUTH_SECRET: <%= ENV['NYPL_OAUTH_SECRET'] %>
PLATFORM_API_URL: <%= ENV['PLATFORM_API_URL'] %>
IS_DRY_RUN:     <%= ENV['IS_DRY_RUN'] %>
SMTP_DOMAIN:    <%= ENV['SMTP_DOMAIN'] %>
SMTP_USER_NAME: <%= ENV['SMTP_USER_NAME'] %>
SMTP_PASSWORD:  <%= ENV['SMTP_PASSWORD'] %>
